version: '3'

services:
  hadoop:
    container_name: hadoop
    image: sequenceiq/hadoop-docker:2.7.1
    hostname: localhost
    stdin_open: true
    tty: true
    ports:
      - 50070:50070
      - 50075:50075
    command: "/etc/bootstrap.sh -bash"
